In [ ]:
# Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
# Importing the dataset

In [2]:
dataset = pd.read_csv('ford.csv')
print(dataset.head())
X = dataset.iloc[:, [0,1,3,4,5,6,7,8]].values
y = dataset.iloc[:, 2].values

     model  year  price transmission  mileage fuelType  tax   mpg  engineSize
0   Fiesta  2017  12000    Automatic    15944   Petrol  150  57.7         1.0
1    Focus  2018  14000       Manual     9083   Petrol  150  57.7         1.0
2    Focus  2017  13000       Manual    12456   Petrol  150  57.7         1.0
3   Fiesta  2019  17500       Manual    10460   Petrol  145  40.3         1.5
4   Fiesta  2019  16500    Automatic     1482   Petrol  145  48.7         1.0


In [3]:
print(X)

[[' Fiesta' 2017 'Automatic' ... 150 57.7 1.0]
 [' Focus' 2018 'Manual' ... 150 57.7 1.0]
 [' Focus' 2017 'Manual' ... 150 57.7 1.0]
 ...
 [' B-MAX' 2014 'Manual' ... 30 57.7 1.0]
 [' Focus' 2015 'Manual' ... 20 67.3 1.6]
 [' KA' 2018 'Manual' ... 145 57.7 1.2]]


In [4]:
print(y)

[12000 14000 13000 ...  7499  9999  8299]


In [ ]:
# Encoding the categorical data

In [5]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:,0] = le.fit_transform(X[:,0])
X[:,2] = le.fit_transform(X[:,2])
X[:,4] = le.fit_transform(X[:,4])

In [ ]:
# Splitting the dataset into training and test set

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [7]:
print(X_train)

[[5 2018 1 ... 150 88.3 1.5]
 [14 2015 1 ... 145 48.7 1.5]
 [6 2019 0 ... 145 74.3 1.5]
 ...
 [6 2018 1 ... 145 60.1 1.0]
 [2 2019 1 ... 145 53.3 1.0]
 [6 2016 2 ... 125 51.4 1.0]]


In [8]:
print(X_test)

[[14 2017 1 ... 145 48.7 1.5]
 [14 2014 1 ... 30 61.4 2.0]
 [5 2010 1 ... 20 68.9 1.6]
 ...
 [6 2011 0 ... 205 42.2 1.6]
 [5 2019 1 ... 145 58.9 1.0]
 [5 2018 1 ... 150 65.7 1.0]]


In [9]:
print(y_train)

[10995 12950 17699 ... 11250 15990 10998]


In [10]:
print(y_test)

[11298  8995  4750 ...  3995 14320 11999]


In [ ]:
# Feature Scaling by Standardisation

In [11]:
y_train = y_train.reshape(len(y_train),1)

In [12]:
y_test = y_test.reshape(len(y_test),1)

In [13]:
print(y_train)

[[10995]
 [12950]
 [17699]
 ...
 [11250]
 [15990]
 [10998]]


In [14]:
print(y_test)

[[11298]
 [ 8995]
 [ 4750]
 ...
 [ 3995]
 [14320]
 [11999]]


In [15]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
sc_y = StandardScaler()
X_train[:,[0,1,3,4,5,6,7]] = sc_X.fit_transform(X_train[:,[0,1,3,4,5,6,7]])
X_test[:,[0,1,3,4,5,6,7]] = sc_X.fit_transform(X_test[:,[0,1,3,4,5,6,7]])
y_train = sc_y.fit_transform(y_train)
y_test = sc_y.fit_transform(y_test)

/opt/anaconda3/envs/tfdeeplearning/lib/python3.6/site-packages/sklearn/utils/validation.py:444: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
/opt/anaconda3/envs/tfdeeplearning/lib/python3.6/site-packages/sklearn/utils/validation.py:444: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [16]:
print(X_train)

[[-0.46394105477514297 0.5489912031502555 1 ... 0.5899303103447131
  2.973127184449955 0.34899175902482427]
 [1.7752323613836323 -0.9082706767381422 1 ... 0.509516041645759
  -0.9035456029032669 0.34899175902482427]
 [-0.21514400853527904 1.0347451631130549 0 ... 0.509516041645759
  1.6025863000321492 0.34899175902482427]
 ...
 [-0.21514400853527904 0.5489912031502555 1 ... 0.509516041645759
  0.21246626012266073 -0.8166390940322924]
 [-1.2103321934947346 1.0347451631130549 1 ... 0.509516041645759
  -0.45322502659455977 -0.8166390940322924]
 [-0.21514400853527904 -0.42251671677534297 2 ... 0.187858966849943
  -0.6392270037655475 -0.8166390940322924]]


In [17]:
print(X_test)

[[1.8162368021285207 0.07260172725802629 1 ... 0.5153460508883777
  -0.9340440228689167 0.32994566237698625]
 [1.8162368021285207 -1.4151815771420586 1 ... -1.3598546139596979
  0.3671837731162166 1.4517234490163815]
 [-0.44754863845234466 -3.398892649675505 1 ... -1.5229155413377913
  1.1356253849184617 0.5543012197048656]
 ...
 [-0.19601692283224853 -2.9029648815421436 0 ... 1.4937116151569387
  -1.6000267530975285 0.5543012197048656]
 [-0.44754863845234466 1.0644572635247496 1 ... 0.5153460508883777
  0.11103656918213514 -0.7918321242624091]
 [-0.44754863845234466 0.568529495391388 1 ... 0.5968765145774244
  0.8077569638828371 -0.7918321242624091]]


In [18]:
print(y_train)

[[-0.27184711]
 [ 0.13935042]
 [ 1.13821335]
 ...
 [-0.21821265]
 [ 0.77875731]
 [-0.27121612]]


In [19]:
print(y_test)

[[-0.20283041]
 [-0.69407075]
 [-1.5995485 ]
 ...
 [-1.76059343]
 [ 0.44177589]
 [-0.05330393]]


In [70]:
# Training the Random Forest model on the training set

In [20]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators = 10) # taking no. of trees as 10
regressor.fit(X_train, y_train)

/opt/anaconda3/envs/tfdeeplearning/lib/python3.6/site-packages/sklearn/ensemble/weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d
/opt/anaconda3/envs/tfdeeplearning/lib/python3.6/site-packages/ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
           oob_score=False, random_state=None, verbose=0, warm_start=False)

In [ ]:
# Predicting the Test set results

In [21]:
y_pred = sc_y.inverse_transform(regressor.predict(X_test))

In [22]:
print(y_pred)

[10246.66613629  7649.93697167  3144.52713147 ...  5370.65771632
 14466.87025137 11302.50293216]


In [ ]:
# Predicting a new result

In [26]:
model = 'Fiesta'
year = 2018
transmission = 'Manual'
mileage = 13500
fuel = 'Petrol'
tax = 130
mpg = 52.3
engine = 1.5
predicted_price = sc_y.inverse_transform(regressor.predict([[5,year,1,mileage,4,tax,mpg,engine]]))
print('Predicted Price: ', predicted_price)

Predicted Price:  [23223.28627705]


In [ ]:
# Saving the Trained model

In [24]:
import pickle
pickle_out = open("regressor_model.pkl", "wb")
pickle.dump(regressor, pickle_out)
pickle_out.close()

In [ ]:
# Evaluating the model performance

In [28]:
from sklearn.metrics import r2_score
r2_score(sc_y.inverse_transform(y_test), y_pred)

0.9145552216526944